language: python
cache:
  directories:
    - node_modules
install:
  - "if [[ \"$GROUP\" == js ]] ; then npm -v ; fi"
  - "if [[ \"$GROUP\" == js ]] ; then npm install --prefix js/ ; fi"
  - "if [[ \"$GROUP\" == python ]] ; then pip install -U pip ; fi"
  - "if [[ \"$GROUP\" == python ]] ; then pip install -r requirements.txt ; fi"
  - "if [[ \"$GROUP\" == python ]] ; then pip install -r test-requirements.txt ; fi"
script:
  - "if [[ \"$GROUP\" == js ]] ; then npm run --prefix js/ lint ; fi"
  - "if [[ \"$GROUP\" == python ]] ; then flake8 gmaps ; fi"
  - "if [[ \"$GROUP\" == python ]] ; then py.test ; fi"
matrix:
  include:
    - python: 3.6
      env: GROUP=python
    - python: 3.5
      env: GROUP=python
    - python: 2.7
      env: GROUP=python
    - python: 3.6
      env: GROUP=js
